### ISSUE TITLE
[Todo] Add experimental stream of finished games from broadcasts to Square Off GKS using Lichess API

### ISSUE THREAD

**Issue by eqikkwkp25-cyber** [greghope667/square-off-remote#4]
Hello @greghope667 , 

I see you are active before Christmas, I'll take a look at the changes right away :-) 

Even if I don't see myself as a developer, here is my contribution. Since I can't upload files directly, it might work with an issue and pull request, otherwise I'll just paste the code here. Please review and fine tune. 

Thanks to you.

p.s. Issue is not needed for a PR, just a fork of your repository.

**Comment by eqikkwkp25-cyber** [comment]
See Pull Request [Add experimental stream of finished games from broadcasts to Square Off GKS using Lichess API](https://github.com/greghope667/square-off-remote/pull/5)

**Comment by greghope667** [comment]
Thanks for the contribution, and the kind words :) .

> Even if I don't see myself as a developer, here is my contribution

Contributions from anyone are welcome. And don't sell yourself short - getting a random github project working + adding working code is not trivial.

> Since I can't upload files directly, it might work with an issue and pull request

Issue + PR is the probably the best method for contribution. Or just a PR if it's a small change.

Lichess API integration is certainly something I'm interested in, so I'd definitely like to merge this. I'll do some reviewing/testing and get back to you.

**Comment by eqikkwkp25-cyber** [comment]
Thanks for the motivation. I wanted the demo code out asap :-)  

I see some simple improvements already like considering other operating systems as 'os.system("clear")' will not work on Windows etc.  Need to work on exception handling and code logic (make use of classes). 

Next step could be differentiation between not started, ongoing and finished games and mark those in different colors for instance. 

Lichess API seems to be superior to the chess.com one by far. Nevertheless, one feature I would like to use is "external play with BOT-API" which is deactivated. 

Currently i like watching "live" chess games (video + board). That is the reason why i focused on the APIs broadcasting part. It would be cool if video streams would be in sync with the broadcasted games on Lichess. 

It might be worth discussing what we want to implement.
